### PR TITLE
1. corrected code to build for windows

### PR DESCRIPTION
**Pull request by vikulin**
1. corrected code to build for windows

### CODE REVIEW

**Comment by neilalexander** [comment]
Thanks for this, can you please add a sign-off to your PR comment?
```
Signed-off-by: Your Name <your@email.example.org>
```

**Comment by vikulin** [comment]
Signed-off-by: Vadym Vikulin<vadym.vikulin@gmail.com>

**Comment by vikulin** [comment]
> 
> 
> Thanks for this, can you please add a [sign-off](https://github.com/matrix-org/matrix-doc/blob/master/CONTRIBUTING.rst#sign-off) to your PR comment?
> 
> ```
> Signed-off-by: Your Name <your@email.example.org>
> ```

Done

**Review by neilalexander — APPROVED** [review]
Thanks for this!

**Pull request merged**
